# these are the steps for make file for producing the full rag and cv pipeline

# 1. first install all dependencies
install:
	pip install -r requirements.txt

# 2. Run the Full Pipeline which i have put in src/backend folder
rag:
	python src/pipeline.py

# 3. Run just the API
run-app:
	uvicorn src.app:app --reload

# 4. Clean up logs and cache
clean:
	rm -rf __pycache__
	rm -rf src/__pycache__
	rm -rf flora_cv_model
	rm -rf flora_rag_db